# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Makefile ./test/XMLW1.exe ./test/XMLW1.sql
./test/XMLW1.exe: .fix-multy1
./test/XMLW1.urp: ./Makefile ./lib.urp ./test/XMLW1.ur .cake3/tmp__testXMLW1_in
	cat .cake3/tmp__testXMLW1_in > ./test/XMLW1.urp
.cake3/tmp__testXMLW1_in: ./Makefile
	-rm -rf .cake3/tmp__testXMLW1_in
	echo 'database dbname=XMLW1' >> .cake3/tmp__testXMLW1_in
	echo 'sql .././test/XMLW1.sql' >> .cake3/tmp__testXMLW1_in
	echo 'library ../.' >> .cake3/tmp__testXMLW1_in
	echo '' >> .cake3/tmp__testXMLW1_in
	echo '$$/list' >> .cake3/tmp__testXMLW1_in
	echo '$$/char' >> .cake3/tmp__testXMLW1_in
	echo '$$/string' >> .cake3/tmp__testXMLW1_in
	echo '.././test/XMLW1' >> .cake3/tmp__testXMLW1_in
./lib.urp: ./Makefile ./XMLW.ur ./lib/urweb-monad-pack/lib.urp .cake3/tmp__lib_in
	cat .cake3/tmp__lib_in > ./lib.urp
.cake3/tmp__lib_in: ./Makefile
	-rm -rf .cake3/tmp__lib_in
	echo 'library ./lib/urweb-monad-pack' >> .cake3/tmp__lib_in
	echo '' >> .cake3/tmp__lib_in
	echo './XMLW' >> .cake3/tmp__lib_in
./lib/urweb-monad-pack/lib.urp: ./Makefile ./lib/urweb-monad-pack/error.ur ./lib/urweb-monad-pack/identity.ur ./lib/urweb-monad-pack/pure.ur ./lib/urweb-monad-pack/state.ur .cake3/tmp__liburweb-monad-packlib_in
	cat .cake3/tmp__liburweb-monad-packlib_in > ./lib/urweb-monad-pack/lib.urp
.cake3/tmp__liburweb-monad-packlib_in: ./Makefile
	-rm -rf .cake3/tmp__liburweb-monad-packlib_in
	echo '' >> .cake3/tmp__liburweb-monad-packlib_in
	echo '../.././lib/urweb-monad-pack/error' >> .cake3/tmp__liburweb-monad-packlib_in
	echo '../.././lib/urweb-monad-pack/state' >> .cake3/tmp__liburweb-monad-packlib_in
	echo '../.././lib/urweb-monad-pack/identity' >> .cake3/tmp__liburweb-monad-packlib_in
	echo '../.././lib/urweb-monad-pack/pure' >> .cake3/tmp__liburweb-monad-packlib_in
.PHONY: lib
lib: ./Makefile ./lib.urp
./test/XMLW1.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./Makefile ./test/XMLW1.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./test/XMLW1
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./test/XMLW1.exe
./test/XMLW1.exe: .fix-multy1
.PHONY: ./test/XMLW1.urp
./test/XMLW1.urp: .fix-multy1
.PHONY: .cake3/tmp__testXMLW1_in
.cake3/tmp__testXMLW1_in: .fix-multy1
.PHONY: ./lib.urp
./lib.urp: .fix-multy1
.PHONY: .cake3/tmp__lib_in
.cake3/tmp__lib_in: .fix-multy1
.PHONY: ./lib/urweb-monad-pack/lib.urp
./lib/urweb-monad-pack/lib.urp: .fix-multy1
.PHONY: .cake3/tmp__liburweb-monad-packlib_in
.cake3/tmp__liburweb-monad-packlib_in: .fix-multy1
.PHONY: lib
lib: .fix-multy1
.PHONY: ./test/XMLW1.sql
./test/XMLW1.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./lib.urp ./lib/urweb-monad-pack/lib.urp ./test/XMLW1.exe ./test/XMLW1.sql ./test/XMLW1.urp .cake3/tmp__lib_in .cake3/tmp__liburweb-monad-packlib_in .cake3/tmp__testXMLW1_in
	-rm -rf .cake3

endif
